#!/usr/bin/env bash
#configures a brand new Ubuntu machine
#to the requirements asked in this task
sudo sh -c 'echo "server {
    listen 80;
    server_name _;
    add_header X-Served-By "\$hostname";

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /404.html;
    location 404.html {
        root /var/www/html;
        index 404.html;
    }
}" > /etc/nginx/sites-available/default'
sudo service nginx restart
