#!/usr/bin/env bash
#configures a brand new Ubuntu machine 
#to the requirements asked in this task
sudo sh -c 'echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
        add_header X-Served-By "\$hostname";
    }
}" > /etc/nginx/sites-available/default'
sudo service nginx restart
