#!/usr/bin/env bash
#
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y haproxy

echo sh -c "
	global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend web
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" > /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
haproxy -f /etc/haproxy/haproxy/cfg
