#!/usr/bin/env bash
#script that displays numbers from 1 to 100

i=1

while [ $i -le 100 ]
do
if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ] 
then
echo "FizzBuzz"
((i++))
elif [ $((i % 3)) -eq 0 ]
then
echo "Fizz"
((i++))
elif [ $((i % 5)) -eq 0 ]
then
echo "Buzz"
((i++))
else
echo "$i"
((i++))
fi
done
