#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd

file=/etc/passwd

while IFS= read -r line
do
field1=$(echo "$line" | cut -d ':' -f 1)
field2=$(echo "$line" | cut -d ':' -f 3)
field3=$(echo "$line" | cut -d ':' -f 6)
combine="$field1:$field2:$field3"
echo "$combine"
done < "$file"
